name: build

on:
  push:
  pull_request:

concurrency:
  group: ${{github.workflow}}-${{github.event_name}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint-and-build:
    runs-on: macos-latest
    steps:
      - name: â¤µï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ‰ Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ğŸ“¦ Install Dependencies
        run: npm install

      - name: ğŸš€ Build
        run: npm run build

      - name: âš›ï¸ Install site dependencies
        run: npm --prefix site install

      - name: âœ… Run continuous integration tests
        run: |
          npm run ci

      - name: ğŸ’¡ Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/coverage-final.json
          flags: infographic
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
